# Generated by Django 3.1.5 on 2021-06-21 11:49

from django.db import migrations, models
import django.db.models.deletion
import user_authentication.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'role_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExceptionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('http_status', models.CharField(blank=True, max_length=100, null=True)),
                ('api_url', models.CharField(blank=True, max_length=300, null=True)),
                ('method_name', models.CharField(blank=True, max_length=200, null=True)),
                ('line_no', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=300, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exception_errors',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('expiry_timestamp', models.DateTimeField()),
                ('mobile_no', models.CharField(max_length=10, validators=[user_authentication.validators.validate_mobile_no])),
                ('email_address', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'otp',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('permission', models.CharField(max_length=100)),
                ('permission_desc', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True, verbose_name='self')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(null=True, verbose_name='self')),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=100, unique=True)),
                ('role_desc', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True, verbose_name='self')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(null=True, verbose_name='self')),
                ('permissions', models.ManyToManyField(to='user_management.Permissions')),
            ],
            options={
                'db_table': 'role',
                'ordering': ['pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user_name', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(null=True, verbose_name='self')),
                ('created_by', models.IntegerField(null=True, verbose_name='self')),
                ('mobile_no', models.CharField(max_length=10, validators=[user_authentication.validators.validate_mobile_no])),
                ('roles', models.ManyToManyField(to='user_management.Role')),
            ],
            options={
                'db_table': 'user',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserLoggedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.users')),
            ],
            options={
                'db_table': 'user_logged_in',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserActiveLoggedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('token', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.users')),
            ],
            options={
                'db_table': 'user_active_logged_in',
                'default_permissions': (),
            },
        ),
    ]
